using QuickFuzzr.Tests._Tools;
using QuickPulse.Explains;

namespace QuickFuzzr.Tests.Docs.B_Reference.E_ExtensionMethods.Methods;

[DocFile]
[DocFileHeader("Apply")]
[DocColumn(FuzzrExtensionMethods.Columns.Description,
"Executes a side-effect for, or transform each value generated by the wrapped fuzzr.")]
[DocContent("Executes a side-effect per generated value without altering it.")]
[DocSignature("ExtFuzzr.Apply(this FuzzrOf<T> fuzzr, Action<T> action)")]
public class ExtFuzzrApply
{
    [CodeSnippet]
    [CodeRemove("42")]
    [CodeRemove("return seen;")]
    private static List<int> Apply_Action_PerformsSideEffect_Example()
    {
        var seen = new List<int>();
        var fuzzr = Fuzzr.Int().Apply(seen.Add);
        var value = fuzzr.Generate(42);
        // seen now equals [ 67 ]
        return seen;
    }


    [Fact]
    [DocUsage]
    [DocExample(typeof(ExtFuzzrApply), nameof(Apply_Action_PerformsSideEffect_Example))]
    public void Apply_Action_PerformsSideEffect()
    {
        var seen = Apply_Action_PerformsSideEffect_Example();
        Assert.Single(seen);
        Assert.Equal(67, seen[0]);
    }

    [CodeSnippet]
    [CodeRemove("return ")]
    private static FuzzrOf<int> Apply_Func_TransformsValue_Fuzzr()
    {
        return Fuzzr.Constant(41).Apply(x => x + 1);
        // Results in => 42
    }

    [DocOverloads]
    [DocOverload("Apply(this FuzzrOf<T> fuzzr, Func<T,T> func)")]
    [DocContent("  Transforms generated values while preserving generation context.")]
    [DocExample(typeof(ExtFuzzrApply), nameof(Apply_Func_TransformsValue_Fuzzr))]
    [Fact]
    public void Apply_Func_TransformsValue()
    {
        Assert.Equal(42, Apply_Func_TransformsValue_Fuzzr().Generate());
    }

    [Fact]
    [DocExceptions]
    [DocException("ArgumentNullException", "When the provided `Action` or `Func` is null.")]
    public void Counter_Null_Key()
    {
        var ex = Assert.Throws<ArgumentNullException>(() => Fuzzr.Constant(42).Apply((Action<int>)null!));
        Assert.Equal("Value cannot be null. (Parameter 'action')", ex.Message);
        ex = Assert.Throws<ArgumentNullException>(() => Fuzzr.Constant(42).Apply(null!));
        Assert.Equal("Value cannot be null. (Parameter 'func')", ex.Message);
    }
}

