using QuickFuzzr.Tests._Tools;
using QuickPulse.Explains;

namespace QuickFuzzr.Tests.Docs.B_Reference.C_ExtensionMethods.Methods;

[DocFile]
[DocFileCodeHeader("Apply(this FuzzrOf<T> fuzzr, Action<T> action)")]
[DocColumn(FuzzrExtensionMethods.Columns.Description, "Executes a side-effect for, or transform each value generated by the wrapped fuzzr.")]
public class ExtFuzzrApply
{
    [CodeSnippet]
    [CodeRemove("42")]
    [CodeRemove("return seen;")]
    private static List<int> Apply_Action_PerformsSideEffect_Example()
    {
        var seen = new List<int>();
        var fuzzr = Fuzzr.Int().Apply(seen.Add);
        var value = fuzzr.Generate(42);
        // seen now equals [ 67 ]
        return seen;
    }


    [Fact]
    [DocContent("Executes a side-effect per generated value without altering it.")]
    [DocUsage]
    [DocExample(typeof(ExtFuzzrApply), nameof(Apply_Action_PerformsSideEffect_Example))]
    public void Apply_Action_PerformsSideEffect()
    {
        var seen = Apply_Action_PerformsSideEffect_Example();
        Assert.Single(seen);
        Assert.Equal(67, seen[0]);
    }

    [CodeSnippet]
    [CodeRemove("return ")]
    private static FuzzrOf<int> Apply_Func_TransformsValue_Fuzzr()
    {
        return Fuzzr.Constant(41).Apply(x => x + 1);
        // Results in => 42
    }

    [DocOverloads]
    [DocOverload("Apply(this FuzzrOf<T> fuzzr, Func<T,T> func)")]
    [DocContent("  Transforms generated values while preserving generation context.")]
    [DocExample(typeof(ExtFuzzrApply), nameof(Apply_Func_TransformsValue_Fuzzr))]
    [Fact]
    public void Apply_Func_TransformsValue()
    {
        Assert.Equal(42, Apply_Func_TransformsValue_Fuzzr().Generate());
    }

    [Fact]
    [DocExceptions]
    [DocException("NullReferenceException", "When the provided `Action` or `Func` is null.")]
    public void Counter_Null_Key() // Check: change message
    {
        var ex = Assert.Throws<NullReferenceException>(() => Fuzzr.Constant(42).Apply(null!).Generate());
        Assert.Equal("Object reference not set to an instance of an object.", ex.Message);
    }
}

