using QuickFuzzr.Tests._Tools;
using QuickPulse.Explains;

namespace QuickFuzzr.Tests.Docs.B_Reference.C_ExtensionMethods.Methods;

[DocFile]
[DocFileCodeHeader("ExtFuzzr.Apply(this FuzzrOf<T> fuzzr, Action<T> action)")]
[DocColumn(FuzzrExtensionMethods.Columns.Description, "Executes a side-effect for, or transform each value generated by the wrapped fuzzr.")]
public class ExtFuzzrApply
{

    [DocContent("Executes a side-effect per generated value without altering it.")]
    [Fact]
    [DocUsage]
    public void Apply_Action_PerformsSideEffect_AndKeepsValue()
    {
        var seen = new List<int>();
        var fuzzr = Fuzzr.Int().Apply(seen.Add);
        var value = fuzzr.Generate(42);
        Assert.Single(seen);
        Assert.Equal(seen[0], value);
    }

    [DocOverloads]
    [DocOverload("ExtFuzzr.Apply(this FuzzrOf<T> fuzzr, Func<T,T> func)")]
    [DocContent("  Transforms generated values while preserving generation context.")]
    [Fact]
    public void Apply_Func_TransformsValue()
    {
        var fuzzr = Fuzzr.Constant(41).Apply(x => x + 1);
        Assert.Equal(42, fuzzr.Generate());
    }
}

